_target_: src.models.vicon.vicon_latent_dicon.ViconLatentDICON

backbone:
  _target_: src.models.vicon.vicon.Vicon

  patch_resolution: 64
  patch_num_in: 8
  patch_num_out: 8
  ex_num: ${data.ex_num}
  short_num_min: 1
  dim_channel: 2
  dim_token: 256

  transformer:
    _target_: src.models.base.transformer.TransformerEncoder
    layer:
      _target_: src.models.base.transformer.TransformerEncoderLayer
      d_model: 256
      nhead: 8
      dim_feedforward: 1024
      dropout: 0.0
    num_layers: 6

flow_expert:
  _target_: src.models.vicon.vicon_latent_dicon.LatentImageFlowMatchingExpert
  target_channels: 2
  cond_channels: ${model.backbone.dim_token}
  hidden_channels: 128
  num_layers: 4

backbone_ckpt_path: null
freeze_backbone: false
backbone_strict: true