# @package _global_

defaults:
  - data/pdearena/pdearena@data
  - model: vicon_transformer_video
  - plmodule: ltx_vicon
  - datamodule: base
  - loss: none
  - opt: default
  - accelerate: default
  - callbacks: many_callbacks
  - logger: many_loggers
  - trainer: ddp
  - paths: default
  - extras: default
  - hydra: default
  - _self_
  - experiment: null
  - hparams_search: null
  - optional local: default
  - debug: null

task_name: "train"
tags: ["pdearena", "pretrained_vicon", "video_transformer", "next_frame"]
train: True
test: false
seed: 42
print_lv: 1
log_project: "pdearena"

accelerate:
  precision: bf16-mixed

opt:
  optimizer:
    lr: 1e-4

trainer:
  max_steps: 100000
  val_check_interval: 5000
