#######################################################
# This file belongs to the core repository.
# If your project repository is a fork of core,
# you are suggested to keep this file untouched in your project.
# This helps avoid merge conflicts when syncing from core.
#######################################################

# @package _global_

defaults:
  - data/ks/ks@data
  - model: dicon
  - plmodule: dicon
  - datamodule: base
  - loss: icon
  - opt: default
  - accelerate: default
  - callbacks: many_callbacks
  - logger: many_loggers
  - trainer: ddp
  - paths: default
  - extras: default
  - hydra: default
  - _self_

  - experiment: null
  - hparams_search: null
  - optional local: default
  - debug: null

task_name: "train"
tags: ["dicon", "flow_matching", "ks", "long_prompt"]
train: True
test: false
seed: 42
print_lv: 1
log_project: "dicon"

model:
  backbone:
    shot_num_min: 3

loss:
  shot_num_min: 3

opt:
  optimizer:
    lr: 2e-4
